### ISSUE TITLE
Select an email service

### ISSUE THREAD

**Issue by Hevia** [centerforbiologicaldiversity/SpeciesWeb#3]
The cookiecutter django project provides several preconfigured options for email services.

Here is a list.
- Mailjet
- Mandrill
- Postmark
- Sendgrid
- SendinBlue
- SparkPost
- In-house solution

We need to select which one we will be using for sending confirmation emails to accounts, etc

**Comment by RkirkCBD** [comment]
I'll send over a Sendgrid api key

**Comment by Hevia** [comment]
Thanks! I got it
